### PR TITLE
46 create volunteerroles in createevent modal

### LINKED ISSUE #46: Create VolunteerRoles in CreateEvent modal
It should be similar to the addQuestions component
Add roles (like adding multiple choice questions), then add shifts for each role (also like adding MCQ’s, but have to select role from dropdown first)

Image

### PR DESCRIPTION
**Pull request by Bdon101**
## Developer: Brandon Eng, Grace Boye-Williams

Closes #46 

### Pull Request Summary

- Captures a list of VolunteerRoles and rerenders the VolunteerRoles component through state management.
- Renders a list of roles names and allows for adding roles to VolunteerRoles component.
- Shifts allow for selection of certain role and displays list of shift start times and end times for each role. 
- Use of event handlers and state management to allow user to edit any role and delete roles.

### Modifications

- made folder app/components/VolunteerRoles
- inside AddQuestions folder
     - added VolunteerRoles.tsx: displays list of formatted roles and allows for making changes to roles
     - added VolunteerRoles.module.css: basic styling for volunteer roles

### Testing Considerations

- Verify that user can properly add volunteer roles
- Verify that user can change roles after they have been added
- Verify that roles added are displayed in shifts selection
- Verify that start and end times can be added and changed for each shift within each role
- Verify that roles and shifts can be properly deleted

### Pull Request Checklist

- [x] Code is neat, readable, and works
- [x] Comments are appropriate
- [x] The commit messages follows our [guidelines](https://h4i.notion.site/Conventional-Commits-593452ad1179489399ad3bd696ef772a)
- [x] The developer name is specified
- [x] The summary is completed
- [x] Assign reviewers

### Screenshots/Screencast
Screenshot 2024-04-30 at 1 56 50 PM

### CODE REVIEW

**Comment by andrewtchan** [comment]
image
Getting this error when submitting a new event. The api calls went through though.

**Review by andrewtchan — CHANGES_REQUESTED** [review]
Looks pretty solid, and I know there was some tricky stuff about this issue so really really great work this helps us a ton. Before we merge this please take a look at my comment, there's an error when submitting the new event. I think this could be a problem with the CreateEvent modal logic. 

ALSO: we need to change the handleSubmit there to post the new roles to the VolunteerRoles collection and then update the roles array in the new Event document. This can get a little tricky since the Event document and Role documents have id references to each other, so you'll have to do a PUT on the event or roles to update it with the newly created Role id's. You can see the current logic doing this exact process for VolunteerForm.

**Comment by Bdon101** [comment]
For the runtime error with the timeslots, what did you test to get that error. Is it an error with indexing when shifts are deleted or just in general when you submit an event. Or is this error related to not doing a PUT on the event or roles to update it with the newly created Role id's

**Comment by andrewtchan** [comment]
I created an event and added/deleted a couple roles and added/deleted a couple questions. When I submitted it the api calls went through and then that error came up. Might be something to do with the inputs being cleared after submission (this happens in CreateEvent)?

**Comment by Bdon101** [comment]
I think it may have something to do with the index changing. I'll also look into the PUT method for the createevents.

**Review by andrewtchan — APPROVED** [review]
Really great work, this is a hugely important feature for our site. Everything feels responsive functionality-wise. Couple notes (for record keeping purposes, changes will be addressed in another issue):
- Need to add ability to choose location
- Need to add and display role descriptions
- Need to update styling & spacing

I fixed some of the endpoints to have the correct status codes on success, was breaking your api call chains in this component. Also removed some extra logging statements (assume were being used for development).

**Pull request merged**
