### PR TITLE
53 create volunteer profile page

### LINKED ISSUE #53: Create Volunteer Profile Page
Image

  - Page not modal
  - [x] Use MUI datagrid with pagination and scroll
    - Also default sort by date
  - Should be very similar to the Profile Database component
  - [x] Load profile picture from Clerk user data would be sweet
    - https://clerk.com/docs/references/nextjs/read-session-data 
- No design… 🙁 but we also want to have a few general questions for all users to generate tags
  - [x] Make a section above Upcoming Events
  - Then create the questions there https://react-select.com/home 
    - [x] What languages do you speak? (multi select)
      - Spanish proficient
      - Spanish limited working proficiency
      - English proficient
      - Etc.
  - [ ] What types of events are you interested in? (multi select)
    - Clinics, outreach, etc.
    - Do you have expertise/experience in any of the following? (multi select)
    - Immigration law
    - Running social media accounts
    - Etc.
- [x] Add a “save preferences” button
  - This will make a put to Volunteer
  - add strings "Spanish", "Legal expertise", etc. to tags attribute in Volunteer (array) *replace languages attribute
  - At minimum get the button working & just print the data you would PUT to console or something
- Extending the issue
  - [x] Update volunteer schema (update existing endpoints where necessary too)
  - [x] Make the PUT call in your button click handler
  - [x] Load the preferences from the database (GET to Volunteer based on the Clerk user email) and populate the questions with those saved responses

### PR DESCRIPTION
**Pull request by andrewtchan**
## Developer: Grace Boye-Williams, Andrew Chan

Closes #53 

### Pull Request Summary

Changes requested in Issue 53 (Create Volunteer Profile Page)

### Modifications

- Create volunteer profile page, route `/volunteerProfile`
- Display Clerk profile picture
- Use MUI datagrid to display all roles volunteer signed up for
- Add profile questions (using Chakra React Select) to allow volunteers to add tags for themselves
- Load and save tags to Volunteer document
- Update Volunteer schema and endpoints to replace languages (string[]) field with tags (string[])

### Testing Considerations

- Can view all roles signed up for
- Can see Clerk profile picture
- Can select different combinations of tags
- Can save tags, updates Volunteer document
- Loads tags correctly when exiting/re-entering the profile page

### Pull Request Checklist

- [x] Code is neat, readable, and works
- [x] Comments are appropriate
- [x] The commit messages follows our [guidelines](https://h4i.notion.site/Conventional-Commits-593452ad1179489399ad3bd696ef772a)
- [x] The developer name is specified
- [x] The summary is completed
- [x] Assign reviewers

### Screenshots/Screencast

image

### CODE REVIEW

**Comment by andrewtchan** [comment]
Add shift times to event history

**Review by hnadrian — CHANGES_REQUESTED** [review]
Need to add a column for shift times. Top quality work as usual

**Comment by andrewtchan** [comment]
@hnadrian Ready for review

**Review by hnadrian — APPROVED** [review]
time shifts looking good and ready to be merged

**Pull request merged**
