### PR TITLE
09 create volunteer endpoints (repost)

### LINKED ISSUE #9: Create endpoints for Volunteer
Create the following endpoints with the specified URLs:
- [x] Create a Volunteer (api/volunteer) POST
- [x] Retrieve all volunteers (api/volunteer) GET
- [x] Retrieve one specific volunteer (api/volunteer/\<id\>) GET
- [x] Retrieve all VolunteerRoles of one volunteer (api/volunteer/\<id\>/roles)  GET
- [x] Edit a volunteer (api/volunteer/\<id\>) PUT

### PR DESCRIPTION
**Pull request by hnadrian**
## Developer: Xavier Garcia

Closes #9
### Pull Request Summary

In this branch, I have created and tested endpoints:
- POST (api/volunteer): to create a volunteer
- GET (api/volunteer): to retrieve all volunteers
- GET (api/volunteer/\<id\>): to retrieve a specific volunteer
- PUT (api/volunteer/ \<id\>): to edit a volunteer's data
- GET (api/volunteer/\<id\>/roles): to retrieve all VolunteerRoles for one volunteer
- DELETE

### Modifications

Created directories:
- api/volunteer   -> contains route.ts which contains a POST and GET; for HTTP requests regarding all volunteers in DB
- api/volunteer/\<id\>   -> contains route.ts which contains a GET and PUT; for HTTP requests for specific volunteer in DB
- api/volunteer/\<id\>/roles   -> contains route.ts which contains a GET; for HTTP requests for roles within specific volunteer in DB

### Testing Considerations

I used the Boomerang extension to test each endpoint manually with the Mongo Dev DB and a localhost server. Additional tests can be done to confirm my results.

### Pull Request Checklist

- [x] Code is neat, readable, and works
- [x] Comments are appropriate
- [x] The commit messages follows our [guidelines](https://h4i.notion.site/Conventional-Commits-593452ad1179489399ad3bd696ef772a)
- [x] The developer name is specified
- [x] The summary is completed
- [x] Assign reviewers

### CODE REVIEW

**Comment by hnadrian** [comment]
@xgarcia17 I made a new request for your issue. This code should be the same. There is one more endpoint DELETE to implement.

**Comment by andrewtchan** [comment]
@hnadrian I think this is actually more involved. When deleting a Volunteer fully from the database, we have to do the following:

1. Delete all VolunteerEntries associated with them
2. Delete all references to the Volunteer in VolunteerRoles they appear in. This means going into the timeslots array for each of those VolunteerRoles and removing their id from the volunteers array in each timeslot. However, we may not want to delete historical data of Volunteers who volunteered as a role for an event then were deleted from the db. 

Here's what I propose: we add a field "active" which is a boolean to the Volunteer schema. Instead of our delete endpoint actually deleting data, we just set this boolean to False. This way we don't have to go delete references and entries which may be data we actually want to preserve.

Let me know what you think. We can also leave this PR open and come back when this becomes relevant.

**Comment by hnadrian** [comment]
@andrewtchan Thanks for catching this. You're right referencing a nonexistent volunteer is an issue. I agree we should have an `active` boolean for the schema! This means we will also make changes to other endpoints for this PR to include `active` boolean

**Comment by hnadrian** [comment]
Okay, the volunteer schema change with `active` boolean is added. Endpoints got some small changes as a result. Tested with Postman. Waiting for review and merge

**Review by andrewtchan — APPROVED** [review]
Thanks Xavier for getting these off the ground & Adrian for adding those changes we discussed :D

**Pull request merged**
